### ISSUE TITLE
ErrorsContainer

### ISSUE THREAD

**Issue by DovydasNavickas** [SimplrJS/react-forms#86]
`simplr-validation` is already an awesome library. One thing that I struggled while starting using it is showing the errors, which is kind of a main thing for the library.
I think we should create `ErrorsContainer` or sth for an easy errors rendering.

We discussed a bit in Slack with @MartynasZilinskas, so we'll have something soon.

**Comment by DovydasNavickas** [comment]
As talked with @MartynasZilinskas offline, it makes sense to put `ErrorsContainer` into `simplr-forms-dom`, because all needed information is in `simplr-forms` and `simplr-validation` only uses public API to provide validation statuses and error messages, which can be gathered in `simplr-forms-dom` too.

**Comment by MartynasZilinskas** [comment]
Done: https://github.com/SimplrJS/react-forms/commit/72262605080636962cdbab3d616b2ab0dc60dfe1
